services:
  - type: web
    name: ecommerce-backend
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: UPI_ID
        value: srishanth244@okicici
      - key: UPI_NAME
        value: E-commerce
    healthCheckPath: /
